### ISSUE TITLE
Registration include other contribution metadata

### ISSUE THREAD

**Issue by ksonda** [internetofwater/register.geoconnex.us#6]
**Is your feature request related to a problem? Please describe.**
When we ask for contributions at geoconnex.us, we ask them to make a README like this: https://github.com/internetofwater/geoconnex.us/blob/master/namespaces/wade/README.md

There is currently no way for people using register.geoconnex.us to provide such information

**Describe the solution you'd like**
Somehow be able to contribute this information. Perhaps more fields in the form that contribute a file that is not a csv; perhaps a tsv or a markdown template named by the collection name (not just the namespace name) (so as not to confuse the yourls workflow)

**Describe alternatives you've considered**
Make or modify the README in the namespace, seems difficult.

**Additional context**

**Comment by C-Loftus** [comment]
Will take a look at this after #5 is merged and we are happy with it. I feel like more fields in the form are easiest for users and for us as developers. 

>  Make or modify the README in the namespace, seems difficult.

Can't we just upload the readme in the same folder alongside the csv file? Modifying I agree might be a bit more work but wouldn't it be the same process as the csv? And also in the same folder

**Comment by ksonda** [comment]
Can upload a readme file. The current guidance sugggests 1 readme per namespace, whereas orgs using the register.geoconnex.us service would probably require 1 set of metadata per csv, which suggests a markdown file per csv which could be populated via form.

**Comment by C-Loftus** [comment]
Ok so just to clarify:

I can create a form where the user:
* can **upload** one readme.md file per namespace

Once that is done and merged I will add to it so that the user:
* can specify **via a form** metadata for each csv
     * Is there a list of all data we need to extract?
     * Should the metadata be used to create a readme in the same flat directory with the other files in the namespace? Or should this be nested?

**Comment by ksonda** [comment]
1. is ok as interim 

I think a good end-state is the user specifies via form some metadata that creates the readme corresponding the the csv. 

The requested metadata is as follows, including examples:

- Homepage (for the site where the redirects are pointing): https://waterdata.usgs.gov
- Description: All monitoring locations used by the USGS Waterdata system
- Example PID: https://geoconnex.us/usgs/monitoring-location/08383500
- Example redirect target: https://waterdata.usgs.gov/monitoring-location/08383500 
- Contact name: Dave Blodgett
- Contact email: dblodgett@usgs.gov 

We may as well just have a more nested directory structure. eg.

/namespaces/usgs

/namespaces/usgs/csv1

/namespaces/usgs/csv1/csv1.csv and /namespaces/usgs/csv1/README.md

**Comment by ksonda** [comment]
addressed in #9
